# Generated by Django 5.0.7 on 2025-10-21 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookoutbox',
            name='next_attempt_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
