version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: chatboard
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chatpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat -d chatboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and channels
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Web Application
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - POSTGRES_DB=chatboard
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=chatpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - DJANGO_DEBUG=0
      - DJANGO_SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Celery Worker
  celery:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - POSTGRES_DB=chatboard
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=chatpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - DJANGO_DEBUG=0
      - DJANGO_SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: celery -A config worker --loglevel=info

  # Celery Beat (Scheduler)
  celery-beat:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - POSTGRES_DB=chatboard
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=chatpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - DJANGO_DEBUG=0
      - DJANGO_SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: celery -A config beat --loglevel=info

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: