version: "3.9"
# docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: chatboard
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chatpass
    ports: ["55432:5432"]   # <- change host port
    volumes: [pgdata:/var/lib/postgresql/data]


  redis:
    image: redis:7
    ports: ["6379:6379"]

volumes:
  pgdata:
